/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "led.h"
#include "buttonbmp.h"
#include "MainDLG.h"
#include "pwm.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x00)
#define ID_BUTTON_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_1    (GUI_ID_USER + 0x02)
#define ID_BUTTON_2    (GUI_ID_USER + 0x03)
#define ID_BUTTON_3    (GUI_ID_USER + 0x04)
#define ID_BUTTON_4    (GUI_ID_USER + 0x05)
#define ID_BUTTON_5    (GUI_ID_USER + 0x06)
#define ID_BUTTON_6    (GUI_ID_USER + 0x07)
#define ID_BUTTON_7    (GUI_ID_USER + 0x08)
#define ID_BUTTON_8    (GUI_ID_USER + 0x09)
#define ID_BUTTON_9    (GUI_ID_USER + 0x0A)
#define ID_BUTTON_10    (GUI_ID_USER + 0x0B)
#define ID_BUTTON_11    (GUI_ID_USER + 0x0C)
#define ID_BUTTON_12    (GUI_ID_USER + 0x0D)
#define ID_TEXT_0    (GUI_ID_USER + 0x0E)
#define ID_TEXT_1    (GUI_ID_USER + 0x0F)
#define ID_TEXT_2    (GUI_ID_USER + 0x10)
#define ID_TEXT_3    (GUI_ID_USER + 0x11)
#define ID_TEXT_4    (GUI_ID_USER + 0x12)
#define ID_TEXT_5    (GUI_ID_USER + 0x13)
#define ID_TEXT_6    (GUI_ID_USER + 0x14)
#define ID_TEXT_7    (GUI_ID_USER + 0x15)
#define ID_TEXT_8    (GUI_ID_USER + 0x16)
#define ID_TEXT_9    (GUI_ID_USER + 0x17)
#define ID_TEXT_10    (GUI_ID_USER + 0x18)
#define ID_TEXT_11    (GUI_ID_USER + 0x19)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
GUI_BITMAP buttonbmp_tab[2];
WM_HTIMER hTimer_1;

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "LED", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "LED0", ID_BUTTON_0, 105, 40, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "LED1", ID_BUTTON_1, 105, 110, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "LED2", ID_BUTTON_2, 105, 180, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "LED3", ID_BUTTON_3, 105, 250, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "LED4", ID_BUTTON_4, 105, 320, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "LED5", ID_BUTTON_5, 370, 40, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "LED6", ID_BUTTON_6, 370, 110, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "LED7", ID_BUTTON_7, 370, 180, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "LED8", ID_BUTTON_8, 370, 250, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "LED9", ID_BUTTON_9, 370, 320, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Water lamp", ID_BUTTON_10, 645, 100, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Breathing lamp", ID_BUTTON_11, 645, 200, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ESC", ID_BUTTON_12, 670, 1, 100, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "LED0", ID_TEXT_0, 11, 48, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "LED1", ID_TEXT_1, 11, 122, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "LED2", ID_TEXT_2, 7, 192, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "LED3", ID_TEXT_3, 6, 256, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "LED4", ID_TEXT_4, 4, 330, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "LED5", ID_TEXT_5, 276, 48, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "LED6", ID_TEXT_6, 275, 122, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "LED7", ID_TEXT_7, 278, 193, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "LED8", ID_TEXT_8, 276, 264, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "LED9", ID_TEXT_9, 279, 336, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Water lamp", ID_TEXT_10, 517, 112, 108, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Breathing lamp", ID_TEXT_11, 506, 209, 120, 20, 0, 0x0, 0 },

  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
	int i;
	static u8 led0flag=0;
	static u8 led1flag=0;
	static u8 led2flag=0;
	static u8 led3flag=0;
	static u8 led4flag=0;
	static u8 led5flag=0;
	static u8 led6flag=0;
	static u8 led7flag=0;
	static u8 led8flag=0;
	static u8 led9flag=0;
	static u8 mode1=0;
	static u8 mode2=0;
	static u16 led0pwmval=0;    
	static u8 dir=1;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
	case WM_PAINT:
			GUI_SetBkColor(GUI_WHITE);
			GUI_Clear();
			break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'LED'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetTitleHeight(hItem, 20);
	
		  //
    // Initialization of 'LED0'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[0],0,0);
    BUTTON_SetText(hItem, "");
    //
    // Initialization of 'LED1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[0],0,0);
    BUTTON_SetText(hItem, "");
    //
    // Initialization of 'LED2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[0],0,0);
    BUTTON_SetText(hItem, "");
    //
    // Initialization of 'LED3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[0],0,0);
    BUTTON_SetText(hItem, "");
    //
    // Initialization of 'LED4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[0],0,0);
    BUTTON_SetText(hItem, "");
    //
    // Initialization of 'LED5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[0],0,0);
    BUTTON_SetText(hItem, "");
    //
    // Initialization of 'LED6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
		BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[0],0,0);
    BUTTON_SetText(hItem, "");
    //
    // Initialization of 'LED7'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
		BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[0],0,0);
    BUTTON_SetText(hItem, "");
    //
    // Initialization of 'LED8'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
		BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[0],0,0);
    BUTTON_SetText(hItem, "");
    //
    // Initialization of 'LED9'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
		BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[0],0,0);
    BUTTON_SetText(hItem, "");
	 //
    // Initialization of 'Water lamp'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
		BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[0],0,0);
    BUTTON_SetText(hItem, "");
    //
    // Initialization of 'Breathing lamp'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
		BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[0],0,0);
    BUTTON_SetText(hItem, "");
    //
    // Initialization of 'LED0'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'LED1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'LED2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'LED3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'LED4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'LED5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'LED6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'LED7'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'LED8'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'LED9'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Water lamp'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Breathing lamp'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20_1);

    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'LED0'
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				//mode1=0;
				LED0=~LED0;		//LED1反转
				led0flag=~led0flag;
				BUTTON_SetBitmapEx(hItem,0,led0flag?&buttonbmp_tab[1]:&buttonbmp_tab[0],0,0);	

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'LED1'
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				//mode1=0;
				LED1=~LED1;		//LED1反转
				led1flag=~led1flag;
				BUTTON_SetBitmapEx(hItem,0,led1flag?&buttonbmp_tab[1]:&buttonbmp_tab[0],0,0);	

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'LED2'
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				//mode1=0;
				LED2=~LED2;		//LED1反转
				led2flag=~led2flag;
				BUTTON_SetBitmapEx(hItem,0,led2flag?&buttonbmp_tab[1]:&buttonbmp_tab[0],0,0);	
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'LED3'
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				//mode1=0;
				LED3=~LED3;		//LED1反转
				led3flag=~led3flag;
				BUTTON_SetBitmapEx(hItem,0,led3flag?&buttonbmp_tab[1]:&buttonbmp_tab[0],0,0);	
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'LED4'
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				//mode1=0;
				LED4=~LED4;		//LED1反转
				led4flag=~led4flag;
				BUTTON_SetBitmapEx(hItem,0,led4flag?&buttonbmp_tab[1]:&buttonbmp_tab[0],0,0);	
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'LED5'
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				//mode1=0;
				LED5=~LED5;		//LED1反转
				led5flag=~led5flag;
				BUTTON_SetBitmapEx(hItem,0,led5flag?&buttonbmp_tab[1]:&buttonbmp_tab[0],0,0);	
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'LED6'
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				//mode1=0;
				LED6=~LED6;		//LED1反转
				led6flag=~led6flag;
				BUTTON_SetBitmapEx(hItem,0,led6flag?&buttonbmp_tab[1]:&buttonbmp_tab[0],0,0);	
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'LED7'
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				//mode1=0;
				LED7=~LED7;		//LED1反转
				led7flag=~led7flag;
				BUTTON_SetBitmapEx(hItem,0,led7flag?&buttonbmp_tab[1]:&buttonbmp_tab[0],0,0);	
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by 'LED8'
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				//mode1=0;
				LED8=~LED8;		//LED1反转
				led8flag=~led8flag;
				BUTTON_SetBitmapEx(hItem,0,led8flag?&buttonbmp_tab[1]:&buttonbmp_tab[0],0,0);	
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by 'LED9'
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				//mode1=0;
				LED9=~LED9;		//LED1反转
				led9flag=~led9flag;
				BUTTON_SetBitmapEx(hItem,0,led9flag?&buttonbmp_tab[1]:&buttonbmp_tab[0],0,0);	
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by 'Water lamp'
						hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				mode1=~mode1;
				BUTTON_SetBitmapEx(hItem,0,mode1?&buttonbmp_tab[1]:&buttonbmp_tab[0],0,0);	
			if(!mode1)
			{
				for(i=0; i<10; i++)
				{
					if(i<8)
						GPIOB->BSRRL = 0x0040<<i;
					else GPIOF->BSRRL = 0x0200<<(i-8);
				}
			}
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by 'Breathing lamp'
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				mode2=~mode2;
				TIM14_PWM_Init_1(500-1,84-1);
				BUTTON_SetBitmapEx(hItem,0,mode2?&buttonbmp_tab[1]:&buttonbmp_tab[0],0,0);	
				if(!mode2)
				{
					TIM_Cmd(TIM14, DISABLE);  //使能TIM14
					LED_Init();
				}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
		case ID_BUTTON_12: // Notifications sent by 'ESC'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
					WM_DeleteTimer(hTimer_1);
					GUI_EndDialog(pMsg->hWin, 0);
					CreateMain();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
  // USER START (Optionally insert additional message handling)
		case WM_TIMER:
			if(mode1)
			{
				for(i=0; i<10; i++)
				{
					if(i<8)
						GPIOB->BSRRH = 0x0040<<i;
					else GPIOF->BSRRH = 0x0200<<(i-8);
					GUI_Delay(100);
				}
				for(i=0; i<10; i++)
				{
					if(i<8)
						GPIOB->BSRRL = 0x0040<<i;
					else GPIOF->BSRRL = 0x0200<<(i-8);
					GUI_Delay(100);
				}
			}		
			else if(mode2)
			{
				if(dir)led0pwmval+=5;//dir==1 led0pwmval递增
				else led0pwmval-=5;	//dir==0 led0pwmval递减 
				if(led0pwmval>300)dir=0;//led0pwmval到达300后，方向为递减
				if(led0pwmval==0)dir=1;	//led0pwmval递减到0后，方向改为递增
		 
				TIM_SetCompare1(TIM14,led0pwmval);	//修改比较值，修改占空比
			}
			WM_RestartTimer(hTimer_1, 100);
		break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateLED
*/
WM_HWIN CreateLED(void);
WM_HWIN CreateLED(void) {
  WM_HWIN hWin;
	LED_Init();   			//LED初始化
	buttonbmp_tab[0]=bmBUTTONOFF;
	buttonbmp_tab[1]=bmBUTTONON;
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	hTimer_1 = WM_CreateTimer(WM_GetClientWindow(hWin),0,100,0); 
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
