/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "MainDLG.h"
#include <string.h>
#include "stdio.h"
#include "adc.h"
#include "exti.h"
#include "timer.h"
#include "includes.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0   (GUI_ID_USER + 0x00)
#define ID_GRAPH_0   (GUI_ID_USER + 0x01)
#define ID_BUTTON_0   (GUI_ID_USER + 0x02)
#define ID_BUTTON_1   (GUI_ID_USER + 0x03)
#define ID_BUTTON_2   (GUI_ID_USER + 0x04)
#define ID_TEXT_0    (GUI_ID_USER + 0x05)
#define ID_TEXT_1    (GUI_ID_USER + 0x06)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
WM_HTIMER hTimer_5;
static GRAPH_SCALE_Handle hScaleV;   // Handle of vertical scale
static GRAPH_SCALE_Handle hScaleH;   // Handle of horizontal scale
GRAPH_DATA_Handle  _ahDataYT;
extern EXTI_InitTypeDef   EXTI_InitStructure;
u8 Ratio=2;
extern u16 ADC_Data_Buf0[ADC_DataLen];
char Disp5[20];
double fp;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Oscilloscope", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 0, 0, 700, 400, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ESC", ID_BUTTON_0, 710, 0, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Amplification", ID_BUTTON_1, 100, 405, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Reduce", ID_BUTTON_2, 300, 405, 80, 40, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Ratio", ID_TEXT_0, 450, 415, 80, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Fre", ID_TEXT_1, 550, 415, 80, 20, 0, 0x64, 0 },

  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
u8 plainFlag=0;
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
	WM_HWIN hDlg;
  int     NCode;
  int     Id;
	int  i,j;
	double Fre;
  // USER START (Optionally insert additional variables)
	  hDlg = pMsg->hWin;

  // USER END
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Oscilloscope'
    //
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "Ratio:");
    TEXT_SetFont(hItem, GUI_FONT_16_1);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, "Fre:");
    TEXT_SetFont(hItem, GUI_FONT_16_1);
	
		hItem = WM_GetDialogItem(hDlg, ID_GRAPH_0);
    FRAMEWIN_SetTextAlign(hDlg, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetTitleHeight(hDlg, 20);
    // USER START (Optionally insert additional code for further widget initialization)
		GRAPH_SetBorder(hItem,40, 5, 5, 30);
		GRAPH_SetGridVis(hItem,1);
		GRAPH_SetGridFixedX(hItem,1);
		GRAPH_SetGridDistY(hItem,50);
		GRAPH_SetGridDistX(hItem,50);
		hScaleV = GRAPH_SCALE_Create(30, GUI_TA_RIGHT, GRAPH_SCALE_CF_VERTICAL, 50);       //创建和增加垂直范围尺度标签
		GRAPH_SCALE_SetTextColor(hScaleV, GUI_RED);                       //设置标签字体颜色
		GRAPH_AttachScale(hItem, hScaleV);                         //将标签添加到垂直方向
		hScaleH = GRAPH_SCALE_Create(375, GUI_TA_HCENTER, GRAPH_SCALE_CF_HORIZONTAL, 50); //创建和增加水平范围尺度标签
		GRAPH_SCALE_SetTextColor(hScaleH, GUI_RED);                 //设置字体颜色
		GRAPH_AttachScale(hItem, hScaleH);                       //添加到水平方向
	  _ahDataYT = GRAPH_DATA_YT_Create(GUI_DARKGREEN, 650, 0, 600);
		GRAPH_DATA_YT_SetOffY(_ahDataYT,20);

	  GRAPH_AttachData(hItem, _ahDataYT);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'ESC'
      switch(NCode) {
				
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
					
					EXTI_InitStructure.EXTI_LineCmd = DISABLE;//中断线使能
					EXTI_Init(&EXTI_InitStructure);//配置
					TIM_Cmd(TIM3,DISABLE); //使能定时器3
			    TIM_Cmd(TIM2,DISABLE);                                
					TIM_Cmd(TIM5,DISABLE); //使能定时器3

					ADC_Cmd(ADC1, DISABLE);//开启AD转换器	
					ADC_DMACmd(ADC1,DISABLE);
					DMA_Cmd(DMA2_Stream0, DISABLE);
					WM_DeleteTimer(hTimer_5);
					GUI_EndDialog(pMsg->hWin, 0);
					CreateMain();
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Amplification'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				Ratio++;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Reduce'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				if(Ratio>0)
							Ratio--;

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
	case WM_TIMER:
		memset(Disp5,0,20);
		sprintf(Disp5,"Ratio:%d",Ratio);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetText(hItem,Disp5);        // USER END

		memset(Disp5,0,20);
		if(fp<=1000)
		{
			sprintf(Disp5,"Fre:%.2lfHz",fp);	
		}
		if(fp>=1000&&fp<=1000000)
		{
			Fre=fp/1000;
			sprintf(Disp5,"Fre:%.2lfKHz",Fre);	
		}
		else if(fp>=1000000)
		{
			Fre=fp/1000000;
			sprintf(Disp5,"Fre:%.2lfMHz",Fre);	
		}
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, Disp5);
	
		if(plainFlag)
		{
			for(i=0;i<ADC_DataLen;i++)
			{
				for(j=0;j<Ratio;j++)
					GRAPH_DATA_YT_AddValue(_ahDataYT,(I16)ADC_Data_Buf0[i]*1.0/4096*300);
			}
			GUI_Delay(100);
			plainFlag=0;
			EXTI_InitStructure.EXTI_LineCmd = ENABLE;//中断线使能
			EXTI_Init(&EXTI_InitStructure);//配置
		}
		WM_RestartTimer(hTimer_5, 100);
		break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateOscilloscope
*/
WM_HWIN CreateOscilloscope(void);
WM_HWIN CreateOscilloscope(void) {
  WM_HWIN hWin;
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	
	TIM3_Int_Init(10-1,84-1);
	TIM2_CH1_Cap_Init(0xffffffff,0);
	TIM5_Int_Init(10000-1,8400-1);
	EXTIX_Init();
	Adc_Init();         //初始化ADC
	DMA2_Config();
	ADC_RegularChannelConfig(ADC1, 2, 1, ADC_SampleTime_15Cycles );	//ADC1,ADC通道,480个周期,提高采样时间可以提高精确度		
	
	hTimer_5 = WM_CreateTimer(WM_GetClientWindow(hWin),0,100,0); 

  return hWin;
}

// USER START (Optionally insert additional public code)
void DMA2_Stream0_IRQHandler(void) 
{  
	OSIntEnter();
	
	if(DMA_GetITStatus(DMA2_Stream0, DMA_IT_TCIF0))  //??DMA??????  
	{
		DMA_ClearITPendingBit(DMA2_Stream0, DMA_IT_TCIF0);
		plainFlag=1;
		printf("DMA interrupt:\r\n");
		printf("\r\n");
	}
	
	OSIntExit();

}

//定时器3中断服务函数
void TIM5_IRQHandler(void)
{
	OSIntEnter();
	if(TIM_GetITStatus(TIM5,TIM_IT_Update)==SET) //溢出中断
	{
		fp=TIM_GetCounter(TIM2);                   //读取1s内计数器计的CNT值
		TIM_SetCounter(TIM2,0);
	}
	TIM_ClearITPendingBit(TIM5,TIM_IT_Update);  //清除中断标志位
	OSIntExit();
}

// USER END

/*************************** End of file ****************************/
