/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "GRAPH.h"
#include <math.h>
#include "sys.h"
#include "usart.h"
#include "adc.h"
#include "exti.h"

#define ID_FRAMEWIN_0   (GUI_ID_USER + 0x00)
#define ID_GRAPH_0   (GUI_ID_USER + 0x01)


static GRAPH_SCALE_Handle hScaleV;   // Handle of vertical scale
static GRAPH_SCALE_Handle hScaleH;   // Handle of horizontal scale
//static GRAPH_SCALE_Handle  pdataGRP;  // Handle of horizontal scale

#define PI 3.1415926f
#define DEG2RAD (PI / 180)
#define Ratio 2		//波形伸展 >1


static int         _NumPoints=200;
GRAPH_DATA_Handle  _ahDataYT;


extern u16 ADC_Data_Buf0[ADC_DataLen];
extern 	EXTI_InitTypeDef   EXTI_InitStructure;


I16 Point[200];

//static const GUI_COLOR _aColor[3] = {GUI_RED, GUI_DARKGREEN, GUI_MAGENTA};
//static const U8 _aLStyle[3] = {GUI_LS_SOLID, GUI_LS_DOT, GUI_LS_DASH};

void _InitPoints(int NumPoints) {
  int i;
  int r=100;
  int m;
  
  _NumPoints = NumPoints;
  m = 360 / (_NumPoints - 1);
  for (i = 0; i <= _NumPoints - 1; i++) {
	  float rad = m * i*PI / 180;
    Point[i] = (I16)(r * cos(rad)+100);
  }
}

/*********************************************************************
*
*       _cbDialog
*/
WM_HWIN hItem;

static void _cbDialog(WM_MESSAGE * pMsg) {
  // USER START (Optionally insert additional variables)
//  int     NCode;
//  int     Id;
//  int     Value;
//  int     i;
//  int     j;
  WM_HWIN hDlg;
  // USER END
  hDlg = pMsg->hWin;
  switch (pMsg->MsgId) {
  // USER START (Optionally insert additional message handling)
	case WM_INIT_DIALOG:
    hItem = WM_GetDialogItem(hDlg, ID_GRAPH_0);
	GRAPH_SetBorder(hItem,40, 5, 5, 30);

	GRAPH_SetGridVis(hItem,1);

	GRAPH_SetGridFixedX(hItem,1);

	GRAPH_SetGridDistY(hItem,50);

	GRAPH_SetGridDistX(hItem,50);
	hScaleV = GRAPH_SCALE_Create(30, GUI_TA_RIGHT, GRAPH_SCALE_CF_VERTICAL, 50);       //创建和增加垂直范围尺度标签

	GRAPH_SCALE_SetTextColor(hScaleV, GUI_RED);                       //设置标签字体颜色


	GRAPH_AttachScale(hItem, hScaleV);                         //将标签添加到垂直方向

	hScaleH = GRAPH_SCALE_Create(375, GUI_TA_HCENTER, GRAPH_SCALE_CF_HORIZONTAL, 50); //创建和增加水平范围尺度标签

	GRAPH_SCALE_SetTextColor(hScaleH, GUI_RED);                 //设置字体颜色

	GRAPH_AttachScale(hItem, hScaleH);                       //添加到水平方向


//	pdataGRP = GRAPH_DATA_YT_Create(GUI_GREEN, 500/*最大数据个数*/, 0, 0);   //创建一个数据曲线,可创建多个曲线
//
//	GRAPH_AttachData(hItem, pdataGRP);                       //为绘图控件添加数据对象	
	_InitPoints(_NumPoints);
      _ahDataYT = GRAPH_DATA_YT_Create(GUI_DARKGREEN, 650, Point, _NumPoints);

	GRAPH_DATA_YT_SetOffY(_ahDataYT,20);

	  GRAPH_AttachData(hItem, _ahDataYT);


  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}



static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 0, 0, 700, 400, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewin_Oscilloscope(void);
WM_HWIN CreateFramewin_Oscilloscope(void) 
{
  
  WM_HWIN hWin;
	GUI_Init();
  GUI_CURSOR_Show();
  WM_SetDesktopColor(GUI_BLACK);
  #if GUI_SUPPORT_MEMDEV
    WM_SetCreateFlags(WM_CF_MEMDEV);
  #endif
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);

	return hWin;
}

// USER START (Optionally insert additional public code)
u8 plainFlag=0;
void Oscilloscope_Demo(void)
{
	int i,j;
	WM_HWIN hWin;
	TIM3_Int_Init(50-1,84-1);
	EXTIX_Init();
	CreateFramewin_Oscilloscope();
	Adc_Init();         //初始化ADC
	DMA2_Config();
	ADC_RegularChannelConfig(ADC1, 2, 1, ADC_SampleTime_15Cycles );	//ADC1,ADC通道,480个周期,提高采样时间可以提高精确度		
	while(1)
	{
		if(plainFlag)
		{
			for(i=0;i<ADC_DataLen;i++)
			{
				for(j=0;j<Ratio;j++)
					GRAPH_DATA_YT_AddValue(_ahDataYT,(I16)ADC_Data_Buf0[i]*1.0/4096*300);
			}
			GUI_Delay(100);
			plainFlag=0;
			EXTI_InitStructure.EXTI_LineCmd = ENABLE;//中断线使能
			EXTI_Init(&EXTI_InitStructure);//配置
		}
	}
}



void DMA2_Stream0_IRQHandler(void) 
{     
	if(DMA_GetITStatus(DMA2_Stream0, DMA_IT_TCIF0))  //??DMA??????  
	{
		DMA_ClearITPendingBit(DMA2_Stream0, DMA_IT_TCIF0);
		plainFlag=1;
		printf("DMA interrupt:\r\n");
		printf("\r\n");
	}
}


// USER END

/*************************** End of file ****************************/
