/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "sys.h"
#include "stdio.h"
#include <string.h>
#include "MainDLG.h"
#include "pwm.h"
#include "w25qxx.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0   (GUI_ID_USER + 0x00)
#define ID_BUTTON_0   (GUI_ID_USER + 0x01)
#define ID_BUTTON_1   (GUI_ID_USER + 0x02)
#define ID_BUTTON_2   (GUI_ID_USER + 0x03)
#define ID_BUTTON_3   (GUI_ID_USER + 0x04)
#define ID_BUTTON_4   (GUI_ID_USER + 0x05)
#define ID_BUTTON_5   (GUI_ID_USER + 0x06)
#define ID_BUTTON_6   (GUI_ID_USER + 0x07)
#define ID_BUTTON_7   (GUI_ID_USER + 0x08)
#define ID_BUTTON_8   (GUI_ID_USER + 0x09)
#define ID_BUTTON_9   (GUI_ID_USER + 0x0A)
#define ID_BUTTON_10   (GUI_ID_USER + 0x0B)
#define ID_BUTTON_11   (GUI_ID_USER + 0x0C)
#define ID_BUTTON_12   (GUI_ID_USER + 0x0D)
#define ID_BUTTON_13   (GUI_ID_USER + 0x0E)
#define ID_TEXT_0    (GUI_ID_USER + 0x0F)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
WM_HTIMER hTimer_3;
u32 FLASH_SIZE=16*1024*1024;	//FLASH 大小为16字节

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "PWM", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "7", ID_BUTTON_0, 40, 75, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "8", ID_BUTTON_1, 140, 75, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "9", ID_BUTTON_2, 240, 75, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "4", ID_BUTTON_3, 40, 140, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "5", ID_BUTTON_4, 140, 140, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "6", ID_BUTTON_5, 240, 140, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "1", ID_BUTTON_6, 40, 200, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "2", ID_BUTTON_7, 140, 200, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "3", ID_BUTTON_8, 240, 200, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Store", ID_BUTTON_9, 340, 140, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Output", ID_BUTTON_10, 340, 200, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "0", ID_BUTTON_11, 140, 260, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ESC", ID_BUTTON_12, 709, 2, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Backspace", ID_BUTTON_13, 340, 75, 80, 40, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "PWM", ID_TEXT_0, 141, 40, 80, 20, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
u8 duty;
char Disp[20];
// USER END

/*********************************************************************
*
*       _cbDialog
*/

WM_HWIN hItemPWM;
static void _cbDialog(WM_MESSAGE * pMsg) {

  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'PWM'
    //
    hItemPWM = pMsg->hWin;
    FRAMEWIN_SetText(hItemPWM, "PWM");
    FRAMEWIN_SetTextAlign(hItemPWM, GUI_TA_HCENTER | GUI_TA_TOP);
		//
    // Initialization of 'PWM'
    //
    hItemPWM = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItemPWM, "PWM:");
    TEXT_SetTextAlign(hItemPWM, GUI_TA_HCENTER | GUI_TA_TOP);
    TEXT_SetFont(hItemPWM, GUI_FONT_16_1);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by '7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
					duty = duty*10+7;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by '8'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				duty = duty*10+8;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by '9'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				duty = duty*10+9;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by '4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				duty = duty*10+4;
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by '5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				duty = duty*10+5;
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by '6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				duty = duty*10+6;
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by '1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				duty = duty*10+1;
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by '2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				duty = duty*10+2;
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by '3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				duty = duty*10+3;
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by 'Store'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				W25QXX_Write(&duty,FLASH_SIZE-2,1);		//从倒数第100个地址处开始,写入SIZE长度的数据
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by 'Output'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
					TIM_SetCompare1(TIM14,duty);	//修改比较值，修改占空比
					
					duty=0;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by '0'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				duty = duty*10+0;
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_12: // Notifications sent by 'ESC'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				TIM_Cmd(TIM14,DISABLE);
				WM_DeleteTimer(hTimer_3);
					GUI_EndDialog(pMsg->hWin, 0);
					CreateMain();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_13: // Notifications sent by 'Backspace'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				duty = duty/10;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
			case WM_TIMER:
				memset(Disp,0,20);
				sprintf(Disp,"PWM:%d",duty);
				TEXT_SetText(hItemPWM,Disp);        // USER END
				WM_RestartTimer(hTimer_3, 100);
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatePWM
*/
WM_HWIN CreatePWM(void);
WM_HWIN CreatePWM(void) {
  WM_HWIN hWin;
	TIM14_PWM_Init(10-1,84-1);
	W25QXX_Init();
	W25QXX_Read(&duty,FLASH_SIZE-2,1);					//从倒数第100个地址处开始,读出SIZE个字节
	TIM_SetCompare1(TIM14,duty);	//修改比较值，修改占空比
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	hTimer_3 = WM_CreateTimer(WM_GetClientWindow(hWin),0,100,0); 
	return hWin;
}

// USER START (Optionally insert additional public code)
//BUTTO演示函数
//void Pwm_Demo(void)
//{
//	WM_HWIN hWin;
//	TIM14_PWM_Init(10-1,84-1);
//	hWin=CreatePWM();
//	while(1)
//	{
//		memset(Disp,0,20);
//		sprintf(Disp,"PWM:%d",duty);
//		TEXT_SetText(hItemPWM,Disp);        // USER END
//		GUI_Delay(100);
//	}
//}

// USER END

/*************************** End of file ****************************/
