/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "stdio.h"
#include "string.h"
#include "waveoutput.h"
#include "MainDLG.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x00)
#define ID_GRAPH_0    (GUI_ID_USER + 0x01)
#define ID_TEXT_0    (GUI_ID_USER + 0x02)
#define ID_BUTTON_0    (GUI_ID_USER + 0x03)
#define ID_BUTTON_1    (GUI_ID_USER + 0x04)
#define ID_BUTTON_2    (GUI_ID_USER + 0x05)
#define ID_BUTTON_3    (GUI_ID_USER + 0x06)
#define ID_BUTTON_4    (GUI_ID_USER + 0x07)
#define ID_BUTTON_5    (GUI_ID_USER + 0x08)
#define ID_BUTTON_6    (GUI_ID_USER + 0x09)


// USER START (Optionally insert additional defines)
WM_HTIMER hTimer_4;
int frequence=1000;
extern u16 SineWave_Value[256];
extern u16 SawToothWave_Value[256];
extern u16 SquareWave_Value[256];
extern u16 TriangleWave_Value[256];
GRAPH_DATA_Handle  _ahDataYT4;

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Signal", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 65, 35, 256, 145, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Signal", ID_TEXT_0, 145, 193, 80, 20, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Sine Wave", ID_BUTTON_0, 480, 20, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Triangular wave", ID_BUTTON_1, 480, 75, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Square wave", ID_BUTTON_2, 479, 135, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Sawtooth wave", ID_BUTTON_3, 480, 200, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ESC", ID_BUTTON_4, 671, -1, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Frequence++", ID_BUTTON_5, 56, 240, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Frequence--", ID_BUTTON_6, 215, 240, 120, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
	int i;
	char Disp_4[20];
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Signal'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleHeight(hItem, 20);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Signal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetText(hItem, "Frequence: 1kHz");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    // USER START (Optionally insert additional code for further widget initialization)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
    GRAPH_SetBorder(hItem, 0, 0, 0, 0);
	 _ahDataYT4 = GRAPH_DATA_YT_Create(GUI_DARKGREEN, 256, 0, 0);
		  GRAPH_AttachData(hItem, _ahDataYT4);
		for(i=0;i<256;i++)
			GRAPH_DATA_YT_AddValue(_ahDataYT4,(I16)(SineWave_Value[i]*1.0*130/1241+4));
	// USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Sine Wave'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
							SineWave(SinWave);
					for(i=0;i<256;i++)
				{
						GRAPH_DATA_YT_AddValue(_ahDataYT4,(I16)(SineWave_Value[i]*1.0*130/1241+4));
				}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Triangular wave'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
							SineWave(TriangleWave);
						for(i=0;i<256;i++)
				{
						GRAPH_DATA_YT_AddValue(_ahDataYT4,(I16)(TriangleWave_Value[i]*1.0*130/1241+4));
				}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Square wave'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
					SineWave(SquareWave);
				for(i=0;i<256;i++)
				{
						GRAPH_DATA_YT_AddValue(_ahDataYT4,(I16)(SquareWave_Value[i]*1.0*130/1241+4));
				}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Sawtooth wave'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				SineWave(SawToothWave);
				for(i=0;i<256;i++)
				{
						GRAPH_DATA_YT_AddValue(_ahDataYT4,(I16)(SawToothWave_Value[i]*1.0*130/1241+4));
				}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'ESC'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
					DMA_Cmd(DMA1_Stream5, DISABLE);  //使能DMA通道3       
					TIM_Cmd(TIM4, DISABLE);			 //使能TIM2,开始产生波形  
					DAC_Cmd(DAC_Channel_1, DISABLE);	   //使能DAC通道1

					WM_DeleteTimer(hTimer_4);
					GUI_EndDialog(pMsg->hWin, 0);
					CreateMain();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Frequence++'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
					if(frequence<10000)
						frequence+=100;
					Set_WaveFre(frequence);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'Frequence--'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
					if(frequence>1000)
						frequence-=100;
					Set_WaveFre(frequence);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
			case WM_TIMER:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
				memset(Disp_4,0,20);
				sprintf(Disp_4,"Fre:%.1lfkHz",frequence*1.0/1000);
				TEXT_SetText(hItem,Disp_4);        // USER END
						
				WM_RestartTimer(hTimer_4, 100);
			break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSignal
*/
WM_HWIN CreateSignal(void);
WM_HWIN CreateSignal(void) {
  WM_HWIN hWin;

	SineWave_Init(SinWave);
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	
	hTimer_4 = WM_CreateTimer(WM_GetClientWindow(hWin),0,100,0); 

  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
