/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "sys.h"
#include "EmWinHZFont.h"
#include "MainDLG.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0   (GUI_ID_USER + 0x00)
#define ID_BUTTON_0   (GUI_ID_USER + 0x01)
#define ID_BUTTON_1   (GUI_ID_USER + 0x02)
#define ID_BUTTON_2   (GUI_ID_USER + 0x03)
#define ID_BUTTON_3   (GUI_ID_USER + 0x04)
#define ID_BUTTON_4   (GUI_ID_USER + 0x05)
#define ID_BUTTON_5   (GUI_ID_USER + 0x06)
#define ID_BUTTON_6   (GUI_ID_USER + 0x07)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)

u8 UDLR=0;
u8 speed=5;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Welcome", ID_FRAMEWIN_0, 0, 300, 800, 180, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Left", ID_BUTTON_0, 440, 96, 80, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Down", ID_BUTTON_1, 550, 96, 80, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Up", ID_BUTTON_2, 550, 46, 80, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Right", ID_BUTTON_3, 660, 96, 80, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "SPEED++", ID_BUTTON_4, 290, 42, 80, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "SPEED--", ID_BUTTON_5, 290, 94, 80, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ESC", ID_BUTTON_6, 710, 1, 80, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
u16 x=0,y=100, last_x,last_y;
WM_HTIMER hTimer_2;
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Welcome'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleVis(hItem, 0);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Left'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				UDLR = 3;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Down'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				UDLR=2;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Up'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				UDLR=1;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Right'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				UDLR=4;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'SPEED++'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				speed++;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'SPEED--'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				speed--;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'ESC'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
					WM_DeleteTimer(hTimer_2);
					GUI_EndDialog(pMsg->hWin, 0);
					CreateMain();
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
	case WM_TIMER:
		GUI_ClearRect(last_x,last_y,last_x+200,last_y+16);
			last_x=x;
		last_y=y;
		if(UDLR==1)
		{
			GUI_DispStringAt("WELOCME SNInfinite",x,y);
			y-=speed;
		}
		else if(UDLR==2)
		{
			GUI_DispStringAt("WELOCME SNInfinite",x,y);
			y+=speed;
		}
		else if(UDLR==3)
		{
			GUI_DispStringAt("WELOCME SNInfinite",x,y);
			x-=speed;
		}
		else if(UDLR==4)
		{
			GUI_DispStringAt("WELOCME SNInfinite",x,y);
			x+=speed;
		}
		if(x>=800 && x<1000)	x=0;
		else if(x<=0 || x>1000) x=800;
		else if (y>=300 && y<1000) y=0;
		else if (y<=0 || y>=1000) y=300;
		WM_RestartTimer(hTimer_2, 100);
		break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWelcome
*/
WM_HWIN CreateWelcome(void);
WM_HWIN CreateWelcome(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	hTimer_2 = WM_CreateTimer(WM_GetClientWindow(hWin),0,100,0);
	GUI_Delay(100);
	GUI_SetBkColor(GUI_BLACK);		//设置背景颜色
	GUI_ClearRect(0,0,800,300-1);
//	GUI_SetFont(&GUI_Font24_ASCII); //设置字体
	GUI_SetColor(GUI_WHITE);       //设置前景色(如文本，画线等颜色)
	GUI_SetFont(&GUI_FontHZ16);
	GUI_DispStringAt("WoW SNInfinite",10,350);

  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
